import type { ResolvedWritingLanguage } from "./writing-language";

type AiPromptLocale = {
  onlyTarget: string; chapterId: string; chapterTitle: string; chapterOutline: string; notProvided: string;
  suggestedLength: (count: number) => string; hardConstraint: string; textToProcess: string; userRequest: string;
  expand: (title: string) => string; continue: (title: string) => string; logic: string; revise: (title: string) => string;
  outlineSystem: (count: number) => string; outlineInput: (context: string, instruction: string, count: number) => string;
  volumeSystem: (count: number) => string; volumeInput: (context: string, volume: string, instruction: string, count: number) => string;
  nodeSystem: string; nodeInput: (context: string, node: string, instruction: string) => string;
  jsonOutline: string; jsonVolume: string; jsonNode: string;
};

export const aiPromptLocales: Record<ResolvedWritingLanguage, AiPromptLocale> = {
  "zh-CN": {
    onlyTarget: "唯一目标章节", chapterId: "章节 ID", chapterTitle: "章节标题", chapterOutline: "章节大纲", notProvided: "未填写", suggestedLength: (n) => `建议字数：约 ${n} 字（允许上下浮动约 15%）`, hardConstraint: "硬性要求：只能处理这一章。相邻章节仅供衔接，绝不能把上一章或下一章当成写作目标。", textToProcess: "待处理文本", userRequest: "用户要求",
    expand: (t) => `根据资料展开《${t}》。只能写这一章。章节标题已由系统单独保存，绝对不要输出标题、章号或 Chapter N，直接从正文第一句开始。只输出可直接进入正文的文本，不解释过程。`, continue: (t) => `从《${t}》现有正文最后一句之后继续写作。只输出新增的正文段落，不得重复、概括、引用或改写任何已有文字，不要输出章节标题或解释。`, logic: "作为连续性编辑输出检查报告，不要输出改写后的正文。必须区分已有证据、合理推断和资料缺口，引用相关段落或事件，并给出具体修改建议。", revise: (t) => `作为文字编辑改写《${t}》的指定文本。保持事实、人物动机和视角不变，只输出修改后的完整文本。`,
    outlineSystem: (n) => `你是长篇小说总纲编辑。严格尊重硬设定和事件因果。参考范本只用于启发结构与风格，不得复制人物、情节、专有名词或原句。只规划卷级结构，不写章节、场景或正文。必须恰好输出 ${n} 个卷节点，每卷有明确标题和介绍，并覆盖故事推进、转折与结局。`, outlineInput: (c, i, n) => `${c}\n\n用户要求：${i}\n\n再次确认：只输出 ${n} 卷，不要输出章或场景。`, volumeSystem: (n) => `你是长篇小说分卷策划编辑。把指定的一卷细化为恰好 ${n} 个可写作章节，可附场景。每章必须有明确标题和可指导写作的摘要。尊重人物、关系、硬设定和因果，只规划这一卷，不重复其他卷，不写正文。`, volumeInput: (c, v, i, n) => `${c}\n\n待展开的卷：\n${v}\n\n用户要求：${i}\n\n恰好生成 ${n} 章。`, nodeSystem: "你是长篇小说结构编辑。只修改指定的一个大纲节点，尊重硬设定、人物动机和因果链。不要扩写正文或修改其他节点。", nodeInput: (c, n, i) => `${c}\n\n当前节点：\n${n}\n\n用户要求：${i}`, jsonOutline: '只返回 JSON：{"rationale":"...","nodes":[{"type":"volume","title":"...","summary":"..."}]}', jsonVolume: '只返回 JSON：{"rationale":"...","nodes":[{"type":"chapter","title":"...","summary":"..."},{"type":"scene","title":"...","summary":"..."}]}', jsonNode: '只返回 JSON：{"rationale":"...","title":"...","summary":"..."}',
  },
  "zh-TW": {
    onlyTarget: "唯一目標章節", chapterId: "章節 ID", chapterTitle: "章節標題", chapterOutline: "章節大綱", notProvided: "未填寫", suggestedLength: (n) => `建議字數：約 ${n} 字（可上下浮動約 15%）`, hardConstraint: "硬性要求：只能處理本章。相鄰章節僅供銜接，絕不能視為寫作目標。", textToProcess: "待處理文字", userRequest: "使用者要求",
    expand: (t) => `依資料展開《${t}》。只寫本章。標題已由系統另行儲存，不得輸出標題、章號或 Chapter N；直接從正文第一句開始，只輸出可直接使用的正文。`, continue: (t) => `從《${t}》現有正文最後一句之後續寫。只輸出新增段落，不得重複、概括、引用或改寫已有文字，也不要輸出標題或說明。`, logic: "以連續性編輯身分輸出檢查報告，不要重寫正文。區分既有證據、合理推論與資料缺口，引用相關段落或事件並提出具體修正建議。", revise: (t) => `依要求改寫《${t}》的指定文字。保持事實、人物動機與視角不變，只輸出完整修訂稿。`,
    outlineSystem: (n) => `你是長篇小說總綱編輯。嚴格尊重硬設定與事件因果。參考範本僅用於啟發結構與風格，不得複製人物、情節、專有名詞或原句。只規劃卷級結構，不寫章節、場景或正文。必須恰好輸出 ${n} 個卷節點。`, outlineInput: (c, i, n) => `${c}\n\n使用者要求：${i}\n\n只輸出 ${n} 卷，不要輸出章或場景。`, volumeSystem: (n) => `你是分卷策劃編輯。將指定的一卷細化為恰好 ${n} 個可寫作章節，可附場景。每章須有明確標題與摘要；只規劃本卷，不重複其他卷，不寫正文。`, volumeInput: (c, v, i, n) => `${c}\n\n待展開的卷：\n${v}\n\n使用者要求：${i}\n\n恰好產生 ${n} 章。`, nodeSystem: "你是小說結構編輯。只修改指定的大綱節點，尊重硬設定、人物動機與因果，不寫正文或修改其他節點。", nodeInput: (c, n, i) => `${c}\n\n目前節點：\n${n}\n\n使用者要求：${i}`, jsonOutline: '只回傳 JSON：{"rationale":"...","nodes":[{"type":"volume","title":"...","summary":"..."}]}', jsonVolume: '只回傳 JSON：{"rationale":"...","nodes":[{"type":"chapter","title":"...","summary":"..."},{"type":"scene","title":"...","summary":"..."}]}', jsonNode: '只回傳 JSON：{"rationale":"...","title":"...","summary":"..."}',
  },
  en: {
    onlyTarget: "ONLY TARGET CHAPTER", chapterId: "Chapter ID", chapterTitle: "Chapter title", chapterOutline: "Chapter outline", notProvided: "Not provided", suggestedLength: (n) => `Suggested length: approximately ${n} words (±15%)`, hardConstraint: "Hard constraint: Work only on this chapter. Adjacent chapters are continuity references only; never treat them as the writing target.", textToProcess: "TEXT TO PROCESS", userRequest: "USER REQUEST",
    expand: (t) => `Expand “${t}” from the supplied outline and story facts. Write this chapter only. The title is stored separately, so do not output a title, chapter number, or Chapter N; begin with the first narrative sentence. Return only publication-ready prose.`, continue: (t) => `Continue from the exact end of the existing prose in “${t}”. Return only new publication-ready paragraphs. Do not repeat, summarize, quote, or rewrite existing passages. Do not output a title or explanation.`, logic: "Act as a continuity editor. Return a diagnostic report, not revised prose. Distinguish established evidence, reasonable inference, and missing information; cite relevant passages or events and give concrete repair suggestions.", revise: (t) => `Revise the selected text from “${t}” as requested. Preserve facts, character motivation, and point of view. Return only the complete revised text.`,
    outlineSystem: (n) => `You are a long-form fiction outline editor. Respect all hard settings and causality. Use style references only for structural and stylistic inspiration; never copy characters, plot, proper nouns, or wording. Plan volume-level structure only, not chapters, scenes, or prose. Return exactly ${n} volume nodes, each with a clear title and summary covering progression, turns, and ending.`, outlineInput: (c, i, n) => `${c}\n\nUser request: ${i}\n\nFinal constraint: return exactly ${n} volumes and no chapters or scenes.`, volumeSystem: (n) => `You are a long-form fiction structure editor. Expand the specified volume into exactly ${n} writable chapters, with optional scenes. Every chapter needs a clear title and actionable summary. Respect characters, relationships, hard settings, and causality. Plan this volume only; do not repeat other volumes or write prose.`, volumeInput: (c, v, i, n) => `${c}\n\nVOLUME TO EXPAND:\n${v}\n\nUser request: ${i}\n\nGenerate exactly ${n} chapters.`, nodeSystem: "You are a fiction structure editor. Modify only the specified outline node while respecting hard settings, character motivations, and causality. Do not write prose or modify other nodes.", nodeInput: (c, n, i) => `${c}\n\nCURRENT NODE:\n${n}\n\nUSER REQUEST:\n${i}`, jsonOutline: 'Return JSON only: {"rationale":"...","nodes":[{"type":"volume","title":"...","summary":"..."}]}', jsonVolume: 'Return JSON only: {"rationale":"...","nodes":[{"type":"chapter","title":"...","summary":"..."},{"type":"scene","title":"...","summary":"..."}]}', jsonNode: 'Return JSON only: {"rationale":"...","title":"...","summary":"..."}',
  },
  de: {
    onlyTarget: "EINZIGES ZIELKAPITEL", chapterId: "Kapitel-ID", chapterTitle: "Kapiteltitel", chapterOutline: "Kapitelgliederung", notProvided: "Nicht angegeben", suggestedLength: (n) => `Empfohlene Länge: ungefähr ${n} Wörter (±15 %)`, hardConstraint: "Verbindlich: Bearbeite nur dieses Kapitel. Benachbarte Kapitel dienen ausschließlich der Kontinuität.", textToProcess: "ZU BEARBEITENDER TEXT", userRequest: "ANFORDERUNG DES BENUTZERS",
    expand: (t) => `Arbeite „${t}“ anhand der Gliederung und der Fakten zu einem vollständigen Kapitel aus. Gib keinen Titel und keine Kapitelnummer aus; beginne direkt mit dem ersten Erzählsatz. Gib nur druckfertige Prosa zurück.`, continue: (t) => `Setze „${t}“ unmittelbar nach dem letzten vorhandenen Satz fort. Gib nur neue Absätze zurück. Wiederhole, zitiere, fasse oder überarbeite keinen vorhandenen Text und gib keinen Titel aus.`, logic: "Prüfe als Kontinuitätslektor. Gib einen Diagnosebericht statt überarbeiteter Prosa aus. Trenne belegte Fakten, plausible Schlüsse und Lücken; zitiere relevante Stellen und nenne konkrete Korrekturen.", revise: (t) => `Überarbeite den ausgewählten Text aus „${t}“ wie verlangt. Bewahre Fakten, Figurenmotivation und Perspektive. Gib nur den vollständigen überarbeiteten Text zurück.`,
    outlineSystem: (n) => `Du bist Lektor für Romanstrukturen. Beachte verbindliche Weltregeln und Kausalität. Stilvorlagen dienen nur als Inspiration; kopiere keine Figuren, Handlung, Eigennamen oder Formulierungen. Plane ausschließlich die Bandstruktur und gib genau ${n} Bände mit Titel und Zusammenfassung aus.`, outlineInput: (c, i, n) => `${c}\n\nBenutzeranforderung: ${i}\n\nGib genau ${n} Bände und keine Kapitel oder Szenen aus.`, volumeSystem: (n) => `Du bist Strukturlektor. Gliedere den angegebenen Band in genau ${n} schreibbare Kapitel mit optionalen Szenen. Jedes Kapitel braucht Titel und konkrete Zusammenfassung. Plane nur diesen Band und schreibe keine Prosa.`, volumeInput: (c, v, i, n) => `${c}\n\nAUSZUARBEITENDER BAND:\n${v}\n\nBenutzeranforderung: ${i}\n\nErzeuge genau ${n} Kapitel.`, nodeSystem: "Du bist Strukturlektor. Ändere nur den angegebenen Gliederungsknoten unter Beachtung von Weltregeln, Figurenmotivation und Kausalität. Schreibe keine Prosa.", nodeInput: (c, n, i) => `${c}\n\nAKTUELLER KNOTEN:\n${n}\n\nBENUTZERANFORDERUNG:\n${i}`, jsonOutline: 'Gib nur JSON zurück: {"rationale":"...","nodes":[{"type":"volume","title":"...","summary":"..."}]}', jsonVolume: 'Gib nur JSON zurück: {"rationale":"...","nodes":[{"type":"chapter","title":"...","summary":"..."},{"type":"scene","title":"...","summary":"..."}]}', jsonNode: 'Gib nur JSON zurück: {"rationale":"...","title":"...","summary":"..."}',
  },
  es: {
    onlyTarget: "ÚNICO CAPÍTULO OBJETIVO", chapterId: "ID del capítulo", chapterTitle: "Título", chapterOutline: "Esquema del capítulo", notProvided: "No proporcionado", suggestedLength: (n) => `Extensión sugerida: unas ${n} palabras (±15 %)`, hardConstraint: "Restricción: trabaja únicamente en este capítulo. Los capítulos adyacentes solo sirven como referencia de continuidad.", textToProcess: "TEXTO QUE PROCESAR", userRequest: "PETICIÓN DEL USUARIO",
    expand: (t) => `Desarrolla «${t}» a partir del esquema y los hechos. Escribe solo este capítulo. No incluyas título ni número; empieza con la primera frase narrativa y devuelve únicamente prosa lista para publicar.`, continue: (t) => `Continúa «${t}» justo después de la última frase existente. Devuelve solo párrafos nuevos. No repitas, resumas, cites ni reescribas el texto existente y no incluyas título.`, logic: "Actúa como editor de continuidad. Devuelve un informe de diagnóstico, no prosa reescrita. Distingue pruebas, inferencias y lagunas; cita pasajes o eventos y propone correcciones concretas.", revise: (t) => `Revisa el texto seleccionado de «${t}» según la petición. Conserva hechos, motivación y punto de vista. Devuelve solo el texto completo revisado.`,
    outlineSystem: (n) => `Eres editor de estructuras narrativas. Respeta reglas firmes y causalidad. Usa referencias solo como inspiración y no copies personajes, trama, nombres ni frases. Planifica únicamente los volúmenes y devuelve exactamente ${n}, cada uno con título y resumen.`, outlineInput: (c, i, n) => `${c}\n\nPetición del usuario: ${i}\n\nDevuelve exactamente ${n} volúmenes, sin capítulos ni escenas.`, volumeSystem: (n) => `Eres editor estructural. Desarrolla el volumen indicado en exactamente ${n} capítulos escribibles, con escenas opcionales. Cada capítulo necesita título y resumen práctico. Planifica solo este volumen y no escribas prosa.`, volumeInput: (c, v, i, n) => `${c}\n\nVOLUMEN QUE DESARROLLAR:\n${v}\n\nPetición: ${i}\n\nGenera exactamente ${n} capítulos.`, nodeSystem: "Eres editor estructural. Modifica solo el nodo indicado respetando reglas, motivaciones y causalidad. No escribas prosa ni cambies otros nodos.", nodeInput: (c, n, i) => `${c}\n\nNODO ACTUAL:\n${n}\n\nPETICIÓN:\n${i}`, jsonOutline: 'Devuelve solo JSON: {"rationale":"...","nodes":[{"type":"volume","title":"...","summary":"..."}]}', jsonVolume: 'Devuelve solo JSON: {"rationale":"...","nodes":[{"type":"chapter","title":"...","summary":"..."},{"type":"scene","title":"...","summary":"..."}]}', jsonNode: 'Devuelve solo JSON: {"rationale":"...","title":"...","summary":"..."}',
  },
  fr: {
    onlyTarget: "SEUL CHAPITRE CIBLE", chapterId: "ID du chapitre", chapterTitle: "Titre", chapterOutline: "Plan du chapitre", notProvided: "Non fourni", suggestedLength: (n) => `Longueur conseillée : environ ${n} mots (±15 %)`, hardConstraint: "Contrainte : ne travaillez que sur ce chapitre. Les chapitres voisins servent uniquement à la continuité.", textToProcess: "TEXTE À TRAITER", userRequest: "DEMANDE DE L’UTILISATEUR",
    expand: (t) => `Développez « ${t} » à partir du plan et des faits. Écrivez uniquement ce chapitre. N’affichez ni titre ni numéro ; commencez par la première phrase narrative et ne retournez que de la prose prête à publier.`, continue: (t) => `Poursuivez « ${t} » juste après la dernière phrase existante. Retournez uniquement de nouveaux paragraphes. Ne répétez, résumez, citez ou réécrivez aucun passage existant et n’affichez pas de titre.`, logic: "Agissez comme responsable de la continuité. Retournez un rapport de diagnostic, pas une réécriture. Distinguez faits établis, inférences et lacunes ; citez les passages concernés et proposez des corrections concrètes.", revise: (t) => `Révisez le texte sélectionné de « ${t} » selon la demande. Préservez les faits, les motivations et le point de vue. Retournez uniquement le texte révisé complet.`,
    outlineSystem: (n) => `Vous êtes responsable de la structure d’un roman. Respectez les règles fermes et la causalité. Les références ne servent qu’à inspirer le style ; ne copiez ni personnages, intrigue, noms propres ou formulations. Planifiez seulement les tomes et retournez exactement ${n} tomes avec titre et résumé.`, outlineInput: (c, i, n) => `${c}\n\nDemande : ${i}\n\nRetournez exactement ${n} tomes, sans chapitres ni scènes.`, volumeSystem: (n) => `Vous êtes responsable de la structure. Développez le tome indiqué en exactement ${n} chapitres exploitables, avec scènes facultatives. Chaque chapitre exige un titre et un résumé concret. Ne planifiez que ce tome et n’écrivez pas de prose.`, volumeInput: (c, v, i, n) => `${c}\n\nTOME À DÉVELOPPER :\n${v}\n\nDemande : ${i}\n\nGénérez exactement ${n} chapitres.`, nodeSystem: "Vous êtes responsable de la structure. Modifiez uniquement le nœud indiqué en respectant règles, motivations et causalité. N’écrivez pas de prose et ne modifiez aucun autre nœud.", nodeInput: (c, n, i) => `${c}\n\nNŒUD ACTUEL :\n${n}\n\nDEMANDE :\n${i}`, jsonOutline: 'Retournez uniquement du JSON : {"rationale":"...","nodes":[{"type":"volume","title":"...","summary":"..."}]}', jsonVolume: 'Retournez uniquement du JSON : {"rationale":"...","nodes":[{"type":"chapter","title":"...","summary":"..."},{"type":"scene","title":"...","summary":"..."}]}', jsonNode: 'Retournez uniquement du JSON : {"rationale":"...","title":"...","summary":"..."}',
  },
  ja: {
    onlyTarget: "唯一の対象章", chapterId: "章 ID", chapterTitle: "章タイトル", chapterOutline: "章プロット", notProvided: "未設定", suggestedLength: (n) => `推奨分量：約 ${n} 字（±15%）`, hardConstraint: "必須条件：この章だけを扱ってください。前後の章は連続性の参考であり、執筆対象ではありません。", textToProcess: "処理対象テキスト", userRequest: "ユーザーの要望",
    expand: (t) => `プロットと設定に基づいて「${t}」を完全な章にしてください。この章だけを書き、タイトルや章番号は出力せず、本文の第一文から始めて完成原稿のみを返してください。`, continue: (t) => `「${t}」の既存本文の最後の文の直後から続きを書いてください。新しい段落だけを返し、既存文の反復、要約、引用、改稿やタイトル出力はしないでください。`, logic: "連続性編集者として、改稿本文ではなく診断レポートを返してください。確定した証拠、妥当な推測、情報不足を区別し、関連箇所を引用して具体的な修正案を示してください。", revise: (t) => `要望に従って「${t}」の選択テキストを改稿してください。事実、人物の動機、視点を保ち、完全な改稿本文だけを返してください。`,
    outlineSystem: (n) => `長編小説の構成編集者として、確定設定と因果関係を守ってください。参考作品は構成と文体の参考だけに使い、人物、筋書き、固有名詞、表現をコピーしないでください。巻構成だけを計画し、タイトルと要約を持つ巻を正確に ${n} 個返してください。`, outlineInput: (c, i, n) => `${c}\n\nユーザーの要望：${i}\n\n巻を正確に ${n} 個だけ返し、章やシーンは出力しないでください。`, volumeSystem: (n) => `構成編集者として、指定された巻を正確に ${n} 個の執筆可能な章へ展開してください。各章には明確なタイトルと実用的な要約が必要です。この巻だけを計画し、本文は書かないでください。`, volumeInput: (c, v, i, n) => `${c}\n\n展開する巻：\n${v}\n\n要望：${i}\n\n正確に ${n} 章を生成してください。`, nodeSystem: "構成編集者として、確定設定、人物の動機、因果関係を守り、指定されたプロットノードだけを変更してください。本文や他のノードは変更しないでください。", nodeInput: (c, n, i) => `${c}\n\n現在のノード：\n${n}\n\n要望：\n${i}`, jsonOutline: 'JSON のみ返してください：{"rationale":"...","nodes":[{"type":"volume","title":"...","summary":"..."}]}', jsonVolume: 'JSON のみ返してください：{"rationale":"...","nodes":[{"type":"chapter","title":"...","summary":"..."},{"type":"scene","title":"...","summary":"..."}]}', jsonNode: 'JSON のみ返してください：{"rationale":"...","title":"...","summary":"..."}',
  },
  "pt-BR": {
    onlyTarget: "ÚNICO CAPÍTULO-ALVO", chapterId: "ID do capítulo", chapterTitle: "Título", chapterOutline: "Estrutura do capítulo", notProvided: "Não fornecida", suggestedLength: (n) => `Extensão sugerida: cerca de ${n} palavras (±15%)`, hardConstraint: "Restrição: trabalhe somente neste capítulo. Capítulos vizinhos servem apenas como referência de continuidade.", textToProcess: "TEXTO A PROCESSAR", userRequest: "PEDIDO DO USUÁRIO",
    expand: (t) => `Desenvolva “${t}” a partir da estrutura e dos fatos. Escreva apenas este capítulo. Não mostre título nem número; comece pela primeira frase narrativa e retorne somente prosa pronta para publicação.`, continue: (t) => `Continue “${t}” imediatamente após a última frase existente. Retorne apenas novos parágrafos. Não repita, resuma, cite ou reescreva o texto existente e não mostre título.`, logic: "Atue como editor de continuidade. Retorne um relatório de diagnóstico, não prosa reescrita. Diferencie evidências, inferências e lacunas; cite trechos ou eventos e proponha correções concretas.", revise: (t) => `Revise o texto selecionado de “${t}” conforme solicitado. Preserve fatos, motivação e ponto de vista. Retorne somente o texto completo revisado.`,
    outlineSystem: (n) => `Você é editor de estrutura narrativa. Respeite regras firmes e causalidade. Use referências apenas como inspiração; não copie personagens, enredo, nomes ou frases. Planeje apenas os volumes e retorne exatamente ${n}, cada um com título e resumo.`, outlineInput: (c, i, n) => `${c}\n\nPedido do usuário: ${i}\n\nRetorne exatamente ${n} volumes, sem capítulos ou cenas.`, volumeSystem: (n) => `Você é editor estrutural. Desenvolva o volume indicado em exatamente ${n} capítulos escrevíveis, com cenas opcionais. Cada capítulo precisa de título e resumo prático. Planeje apenas este volume e não escreva prosa.`, volumeInput: (c, v, i, n) => `${c}\n\nVOLUME A DESENVOLVER:\n${v}\n\nPedido: ${i}\n\nGere exatamente ${n} capítulos.`, nodeSystem: "Você é editor estrutural. Modifique apenas o nó indicado, respeitando regras, motivações e causalidade. Não escreva prosa nem altere outros nós.", nodeInput: (c, n, i) => `${c}\n\nNÓ ATUAL:\n${n}\n\nPEDIDO:\n${i}`, jsonOutline: 'Retorne apenas JSON: {"rationale":"...","nodes":[{"type":"volume","title":"...","summary":"..."}]}', jsonVolume: 'Retorne apenas JSON: {"rationale":"...","nodes":[{"type":"chapter","title":"...","summary":"..."},{"type":"scene","title":"...","summary":"..."}]}', jsonNode: 'Retorne apenas JSON: {"rationale":"...","title":"...","summary":"..."}',
  },
  it: {
    onlyTarget: "UNICO CAPITOLO OBIETTIVO", chapterId: "ID capitolo", chapterTitle: "Titolo", chapterOutline: "Scaletta del capitolo", notProvided: "Non fornita", suggestedLength: (n) => `Lunghezza consigliata: circa ${n} parole (±15%)`, hardConstraint: "Vincolo: lavora solo su questo capitolo. I capitoli adiacenti servono esclusivamente per la continuità.", textToProcess: "TESTO DA ELABORARE", userRequest: "RICHIESTA DELL’UTENTE",
    expand: (t) => `Sviluppa “${t}” dalla scaletta e dai fatti. Scrivi soltanto questo capitolo. Non mostrare titolo o numero; inizia dalla prima frase narrativa e restituisci solo prosa pronta per la pubblicazione.`, continue: (t) => `Continua “${t}” subito dopo l’ultima frase esistente. Restituisci solo nuovi paragrafi. Non ripetere, riassumere, citare o riscrivere il testo esistente e non mostrare il titolo.`, logic: "Agisci come editor della continuità. Restituisci un rapporto diagnostico, non prosa riscritta. Distingui prove, inferenze e lacune; cita passaggi o eventi e proponi correzioni concrete.", revise: (t) => `Rivedi il testo selezionato di “${t}” come richiesto. Conserva fatti, motivazioni e punto di vista. Restituisci soltanto il testo completo rivisto.`,
    outlineSystem: (n) => `Sei un editor di strutture narrative. Rispetta regole vincolanti e causalità. Usa i riferimenti solo come ispirazione e non copiare personaggi, trama, nomi o frasi. Pianifica soltanto i volumi e restituiscine esattamente ${n}, ciascuno con titolo e riassunto.`, outlineInput: (c, i, n) => `${c}\n\nRichiesta: ${i}\n\nRestituisci esattamente ${n} volumi, senza capitoli o scene.`, volumeSystem: (n) => `Sei un editor strutturale. Sviluppa il volume indicato in esattamente ${n} capitoli scrivibili, con scene facoltative. Ogni capitolo richiede titolo e riassunto operativo. Pianifica solo questo volume e non scrivere prosa.`, volumeInput: (c, v, i, n) => `${c}\n\nVOLUME DA SVILUPPARE:\n${v}\n\nRichiesta: ${i}\n\nGenera esattamente ${n} capitoli.`, nodeSystem: "Sei un editor strutturale. Modifica solo il nodo indicato rispettando regole, motivazioni e causalità. Non scrivere prosa né modificare altri nodi.", nodeInput: (c, n, i) => `${c}\n\nNODO ATTUALE:\n${n}\n\nRICHIESTA:\n${i}`, jsonOutline: 'Restituisci solo JSON: {"rationale":"...","nodes":[{"type":"volume","title":"...","summary":"..."}]}', jsonVolume: 'Restituisci solo JSON: {"rationale":"...","nodes":[{"type":"chapter","title":"...","summary":"..."},{"type":"scene","title":"...","summary":"..."}]}', jsonNode: 'Restituisci solo JSON: {"rationale":"...","title":"...","summary":"..."}',
  },
  ko: {
    onlyTarget: "유일한 대상 장", chapterId: "장 ID", chapterTitle: "장 제목", chapterOutline: "장 개요", notProvided: "미설정", suggestedLength: (n) => `권장 분량: 약 ${n}자(±15%)`, hardConstraint: "필수 조건: 이 장만 작업하세요. 앞뒤 장은 연속성 참고용일 뿐 집필 대상이 아닙니다.", textToProcess: "처리할 텍스트", userRequest: "사용자 요청",
    expand: (t) => `개요와 설정을 바탕으로 “${t}”을 완전한 장으로 작성하세요. 이 장만 쓰고 제목이나 장 번호는 출력하지 말며 첫 서술 문장부터 시작해 출판 가능한 본문만 반환하세요.`, continue: (t) => `“${t}”의 기존 본문 마지막 문장 직후부터 이어 쓰세요. 새 문단만 반환하고 기존 문장을 반복, 요약, 인용, 수정하거나 제목을 출력하지 마세요.`, logic: "연속성 편집자로서 수정 본문이 아닌 진단 보고서를 반환하세요. 확정된 증거, 합리적 추론, 정보 공백을 구분하고 관련 구절이나 사건을 인용해 구체적인 수정안을 제시하세요.", revise: (t) => `요청에 따라 “${t}”의 선택 텍스트를 수정하세요. 사실, 인물 동기와 시점을 유지하고 완전한 수정 본문만 반환하세요.`,
    outlineSystem: (n) => `장편소설 구성 편집자로서 확정 설정과 인과관계를 지키세요. 참고 작품은 구조와 문체 영감에만 사용하고 인물, 줄거리, 고유명사나 표현을 복사하지 마세요. 권 구성만 계획하고 제목과 요약이 있는 권을 정확히 ${n}개 반환하세요.`, outlineInput: (c, i, n) => `${c}\n\n사용자 요청: ${i}\n\n권을 정확히 ${n}개만 반환하고 장이나 장면은 출력하지 마세요.`, volumeSystem: (n) => `구성 편집자로서 지정된 권을 정확히 ${n}개의 집필 가능한 장으로 확장하세요. 각 장에는 명확한 제목과 실용적인 요약이 필요합니다. 이 권만 계획하고 본문은 쓰지 마세요.`, volumeInput: (c, v, i, n) => `${c}\n\n확장할 권:\n${v}\n\n요청: ${i}\n\n정확히 ${n}장을 생성하세요.`, nodeSystem: "구성 편집자로서 확정 설정, 인물 동기와 인과관계를 지키며 지정된 개요 노드만 수정하세요. 본문이나 다른 노드는 수정하지 마세요.", nodeInput: (c, n, i) => `${c}\n\n현재 노드:\n${n}\n\n요청:\n${i}`, jsonOutline: 'JSON만 반환하세요: {"rationale":"...","nodes":[{"type":"volume","title":"...","summary":"..."}]}', jsonVolume: 'JSON만 반환하세요: {"rationale":"...","nodes":[{"type":"chapter","title":"...","summary":"..."},{"type":"scene","title":"...","summary":"..."}]}', jsonNode: 'JSON만 반환하세요: {"rationale":"...","title":"...","summary":"..."}',
  },
};
